### ISSUE TITLE
Generative AI Usage

### ISSUE THREAD

**Issue by RhapsPerhaps** [ronthekiehn/twitter-aura2#16]
Please disclose on the homepage that this uses Generative AI for the prompts. Many people are against its usage but don't have the understanding of code to dig into the app. 

People should not be forced to have an AI reference their data (even just colors) without their consent.

**Comment by 50SACINMYSOCIDGAF** [comment]
They arent forced? Dont use the website? Its as simple as that, Rawn made a free project that he has to pay to run. If you want it without an LLM write your own using a vectordb, dont be narcissistic.

**Comment by ronthekiehn** [comment]
Mmm willing to hear opinions on this, I can add an 'about' section that explains that it uses gemini? 

I'm not too worried about it since only the colors and no profile information is being sent, but could be worth clarifying

**Comment by RhapsPerhaps** [comment]
> Mmm willing to hear opinions on this, I can add an 'about' section that explains that it uses gemini?
> 
> I'm not too worried about it since only the colors and no profile information is being sent, but could be worth clarifying

If you're going to continue to use GenAI for any of the generation, even just the colors, I believe a direct disclaimer on the homepage itself is required, not just in an about section.

Many people on Twitter are upset because they didn't realize AI was used in this and likely would not have generated an aura response if they'd known.

**Comment by ronthekiehn** [comment]
Yeah sounds good - didn't think about artists not wanting their banners or even colors being pumped into AI. will add a disclaimer as well later tn.

**Comment by ronthekiehn** [comment]
Hey - I just pushed a disclaimer and also saw your thread on twitter. Let me know if there is anything I should add or change about the disclaimer!

**Comment by RhapsPerhaps** [comment]
> Hey - I just pushed a disclaimer and also saw your thread on twitter. Let me know if there is anything I should add or change about the disclaimer!

First, thank you for taking the concerns seriously. I believe the disclaimer you added is direct enough that people should now be aware when they visit the site. 

I do believe this is a cool concept so if your intention is to iterate on it further I'd challenge you to consider some of the fun and interesting ways you could create the aura descriptions without relying on Gemini. I believe many people would be excited to see more trends like this that are free of GenAI. (It also would be cheaper on your budget, I'm sure.)

**Comment by ronthekiehn** [comment]
Okay thank you so much! I'm not sure how much more work I will put into this project, but I am considering adding an AI-free mode if I have the time!
