### ISSUE TITLE
doesn't update profile after changing header/pfp

### ISSUE THREAD

**Issue by hanatohoshi** [ronthekiehn/twitter-aura2#19]
exactly like that. i changed my pfp/header and wait for a day, but seems like the username & associated data is hard recorded so the results stay the same?

**Comment by ronthekiehn** [comment]
yeah sorry about that - I made it so it would just pull the profile info from my database temporarily because I was hitting rate limits. I have to make some updates because the database is a mess (#2). For now tho, I'll start allowing repeated profiles again.

**Comment by ronthekiehn** [comment]
should be fixed now! You should be able to change your pfp or banner as much as you want!
